networks:
  data-pipeline-network:
    driver: bridge

x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__CORE__FERNET_KEY: ''
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
  AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
  AIRFLOW__WEBSERVER__RATELIMIT_STORAGE_URI: redis://redis:6379/1
  AIRFLOW__WEBSERVER__AUTH_BACKEND: airflow.www.auth.backend.session
  PYTHONPATH: /opt/airflow/dags:/opt/airflow/plugins:/opt/airflow/src

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.1-python3.10
  user: "1000:0"
  environment:
    <<: *airflow-common-env
  env_file:
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
    - ./.env:/opt/airflow/.env
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  networks:
    - data-pipeline-network

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
    networks:
      - data-pipeline-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "2907:2907"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - data-pipeline-network

  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DB=coal_mining_warehouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ../clickhouse/data:/var/lib/clickhouse/
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - data-pipeline-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse-server
    volumes:
      - ./metabase-data:/metabase-data
    networks:
      - data-pipeline-network

  airflow-init:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Anonymous --lastname User --role Admin --email admin@example.org
      "
    user: "0:0"
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres-db-volume:
  metabase-data: