services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coal_mining
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - "/Users/abdulraffiqurahmanrifli/Documents/test/synapsis/synapsis ai engineer challege datasets/production_logs.sql:/docker-entrypoint-initdb.d/init.sql"

volumes:
  db-data: